### PR TITLE
Complete Budget App with User Authentication and Category Management

### PR DESCRIPTION
**Pull request by CVILLA09**
## Implemented Features
- **User Authentication**: Utilized the Devise gem to secure the app and manage user sessions. Users can now register, log in, and log out, with all data being private and secure.
- **Category Management**: Users can create, view, and delete categories. Each category showcases its name, icon, and the total amount spent.
- **Transaction Management**: Implemented the functionality for users to add and view transactions within categories, with a detailed view of the total amount spent.
- **UI Compliance**: Followed the given design guidelines to ensure the UI is consistent with specified colors, typography, and layout.
- **RESTful Routing**: Structured the app's routing to follow RESTful conventions, enhancing readability and maintainability of the code.

## Technical Details
- **Database**: Configured PostgreSQL as the production and development database.
- **Testing**: Created unit and integration tests for models and controllers to ensure reliability and prevent regressions.
- **Frontend**: Employed ERB for dynamic view templates, ensuring a seamless user experience.
- **Deployment**: The app is deployed to Render and is accessible online for review.

## Database Schema
Followed the ERD diagram to represent the app's data structure, ensuring that the database schema is optimized for efficiency and scalability.

## Code Quality
- Ensured no linter errors and followed best Ruby and Rails practices for clean and maintainable code.
- Implemented N+1 query solutions to optimize database interactions.

## Video Documentation
- Recorded a comprehensive video presenting the app's features, the design, and interesting pieces of code. ([Link](https://www.loom.com/share/9511907168644460af0de551c2e22049?sid=19e482e2-47fc-42db-8c63-97f8e2bdc144))

## Looking Forward
- Eager to receive feedback to improve and learn from the review process.
- Kindly review the changes and provide your valuable feedback.

### CODE REVIEW

**Comment by zieeco** [comment]
# STATUS: INVALID!!!  :x: :x: :x: 

Hi @CVILLA09,


While you made a great effort in this project, unfortunately, I cannot proceed to review your code, please make sure you implement the following changes before you resubmit for review. 

## Required Changes ♻️
_Check the comments below._

- [ ] Here's the [deleted PR you worked on](https://github.com/CVILLA09/budget-app/pull/2), and you deleted my review comment. Kindly revert them.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Invalid Code Review Request **Does not count** into the code reviews limit._
# **INVALID PROJECT**

**Comment by CVILLA09** [comment]
# Request for a New Review and Consideration of Previous Feedback

## Dear Review Team,

I am encountering challenges with the previous reviewer, @zieeco. My concerns are about the relevance of his feedback and a seeming misunderstanding of the functionality of my project.

Initially, I sought a review specifically to address an issue with deploying my application using Render. However, in his review, @zieeco did not address this primary concern. Instead, his feedback focused on unrelated aspects.

For instance, he requested fixes for the '.spec/features' tests, which are passing successfully on my local machine. I've attached a screenshot of the test results to this comment for reference.

Captura de pantalla 2023-12-02 a la(s) 5 18 24 p m

Additionally, there was a request to re-record my project video to discuss "my favorite code," which I believe is not pertinent to the project's core functionality. Comments about minor UI details, like a missing white box inside the 'New Purchase' button, also seemed irrelevant.

I had to independently research and seek help from peers to resolve the deployment issue, which I am pleased to report is now fixed.

I am requesting a new review from someone other than @zieeco. His approach has been unhelpful and has hindered my project's progress. I have put considerable effort into this project, and I seek a fair and constructive evaluation.

### Please review my project independently of @zieeco's comment "STATUS: INVALID!!! ❌ ❌ ❌," as the changes he suggested were either irrelevant or non-issues.

I appreciate your understanding, particularly as we sometimes encounter reviews that lack empathy and hinder rather than help, which should be the primary goal.

Thank you for your time and consideration.

**Comment by KayLemba** [comment]
You are hindering your own progress by not following what the previous code reviewer is telling you. I tried reaching out to you on zoom but I never got a response.

**Review by KayLemba — COMMENTED** [review]
STATUS: INVALID!!! ❌ ❌ ❌

Hi @CVILLA09,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code, please make sure you implement the following changes before you resubmit for review.
Required Changes ♻️

Check the comments below.

     

- [ ] You have submitted a project with the wrong git flow 
For Solo Capstone projects:
* Students should follow the Git Flow.
* There are two options:
    * Students can work on a single feature branch, and when they request a review, they should create the PR and compare that feature branch with the development branch.
    * Alternatively, they can work on multiple feature branches, merge these branches into one that consolidates all the changes, and then create a PR for review that compares this branch that holds all the changes with development.



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Invalid Code Review Request Does not count into the code reviews limit.

**Comment by CVILLA09** [comment]
# Dear Reviewer,

Please help me by giving me clear and easy to follow instructions. What should I do now?

Could you please take this PR as the one necessary to ask for a review? 

I really need some help here and I'm getting such bad luck with the reviewers that either don't want to help me or don't give me the right tools. I expect a good review in this PR please, and I'll be so grateful for you feedback.

**Pull request closed without merging**
